name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npx tsx scripts/sync-appwrite-simple.ts
        env:
          APPWRITE_ENDPOINT: ${{ secrets.APPWRITE_ENDPOINT }}
          APPWRITE_PROJECT_ID: ${{ github.event_name == 'pull_request' && secrets.APPWRITE_PROJECT_ID_PREVIEW || secrets.APPWRITE_PROJECT_ID }}
          APPWRITE_API_KEY: ${{ github.event_name == 'pull_request' && secrets.APPWRITE_API_KEY_PREVIEW || secrets.APPWRITE_API_KEY }}
          APPWRITE_DATABASE_ID: ${{ secrets.APPWRITE_DATABASE_ID }}
      - run: npx tsx scripts/run-migrations.ts
        env:
          APPWRITE_ENDPOINT: ${{ secrets.APPWRITE_ENDPOINT }}
          APPWRITE_PROJECT_ID: ${{ github.event_name == 'pull_request' && secrets.APPWRITE_PROJECT_ID_PREVIEW || secrets.APPWRITE_PROJECT_ID }}
          APPWRITE_API_KEY: ${{ github.event_name == 'pull_request' && secrets.APPWRITE_API_KEY_PREVIEW || secrets.APPWRITE_API_KEY }}
          APPWRITE_DATABASE_ID: ${{ secrets.APPWRITE_DATABASE_ID }}
      - run: npx tsx scripts/seed.ts
        if: ${{ github.event_name == 'pull_request' }}
        env:
          APPWRITE_ENDPOINT: ${{ secrets.APPWRITE_ENDPOINT }}
          APPWRITE_PROJECT_ID: ${{ secrets.APPWRITE_PROJECT_ID_PREVIEW }}
          APPWRITE_API_KEY: ${{ secrets.APPWRITE_API_KEY_PREVIEW }}
          APPWRITE_DATABASE_ID: ${{ secrets.APPWRITE_DATABASE_ID }}
      - run: npm run test:schema
        name: Run Schema Contract Tests
        env:
          APPWRITE_ENDPOINT: ${{ secrets.APPWRITE_ENDPOINT }}
          APPWRITE_PROJECT_ID: ${{ github.event_name == 'pull_request' && secrets.APPWRITE_PROJECT_ID_PREVIEW || secrets.APPWRITE_PROJECT_ID }}
          APPWRITE_API_KEY: ${{ github.event_name == 'pull_request' && secrets.APPWRITE_API_KEY_PREVIEW || secrets.APPWRITE_API_KEY }}
          APPWRITE_DATABASE_ID: ${{ secrets.APPWRITE_DATABASE_ID }}